In [6]:
import numpy as np
arr=np.array([1,2,3,4])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr2)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [8]:
np.zeros((3,4))    #creates array with 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((5,2))    #creates array with 1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.full((3,3),4)   #creates 3x3 array filled with 4

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [14]:
np.eye(3)    #creates identity ,atrix of order 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(1,100,10)   #creates array from 1-100 by adding 10

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [20]:
np.linspace(1,100,5)     #equally spaced array  between two entries

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [30]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
myarr.shape    #4x3 matrix

(4, 3)

In [33]:
myarr.size

12

In [36]:
myarr.ndim    #2d array

2

In [38]:
myarr.dtype

dtype('int64')

In [40]:
myarr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype='float32')   #explicit type conversion
myarr2

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [41]:
myarr2.dtype

dtype('float32')

In [46]:
n=myarr2.astype(int)
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
n.dtype

dtype('int64')

In [47]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr.shape

(4, 3)

In [50]:
reshaped=myarr.reshape((2,6))    #reshapes the array into given rows&columns of same size (12 ele)
reshaped

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [51]:
myarr.flatten()   #converts multid arr to 1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])