In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [2]:
flatten=arr.flatten()
flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
flatten[0]

np.int64(1)

In [4]:
flatten[3:5]

array([4, 5])

In [5]:
flatten[6:]

array([ 7,  8,  9, 10, 11, 12])

In [6]:
flatten[::2]

array([ 1,  3,  5,  7,  9, 11])

In [7]:
new=flatten[4:9]
new

array([5, 6, 7, 8, 9])

In [8]:
new[0]

np.int64(5)

In [9]:
new[0]=5555555

In [10]:
new

array([5555555,       6,       7,       8,       9])

In [11]:
flatten   #flatten also changes cuz numpy doesnot copies ,,it refers to same location

array([      1,       2,       3,       4, 5555555,       6,       7,
             8,       9,      10,      11,      12])

In [12]:
new2=flatten[4:7].copy()
new

array([5555555,       6,       7,       8,       9])

In [13]:
new2[0]=99999
new2

array([99999,     6,     7])

In [14]:
new

array([5555555,       6,       7,       8,       9])

In [16]:
# Fancy indexing

In [17]:
new

array([5555555,       6,       7,       8,       9])

In [19]:
new[[1,3,4]]    #returns element of this particular index

array([6, 8, 9])

In [24]:
#boolean masking

In [25]:
new[new>7]    #elements greater than 7

array([5555555,       8,       9])