In [2]:
import numpy as np

In [4]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.sum(arr,axis=0)  #1+4+7,,,2+5+8......

array([12, 15, 18])

In [8]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [11]:
arr[0][2]

np.int64(3)

In [12]:
arr[0,2]

np.int64(3)

In [18]:
arr[0:1]

array([[1, 2, 3]])

In [24]:
arr[0:2,1:3]   #row strt:row end,,,,,,clostart:col end --->end not included

array([[2, 3],
       [5, 6]])

#3D array

In [25]:
# (depth,row,col)

In [41]:
TD=np.array([
    [
        [1,2,3],[4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],[13,14,15],
        [16,17,18]
    ]
])
TD

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [31]:
TD.ndim

3

In [43]:
print(TD[1,2,2])

18


In [39]:
print(TD[:,0:2,1:3])

[[[2 3]
  [5 6]]]


In [48]:
first_row=arr[0,:]
print(first_row)

[1 2 3]


In [51]:
first_clo=arr[:,0]
first_clo

array([1, 4, 7])

In [53]:
fir_row=TD[0,0,:]
fir_row

array([1, 2, 3])

In [54]:
#changin row 

In [55]:
TD

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [59]:
TD[1,1,:]=0     #first depth first row first col=0
TD

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [ 0,  0,  0],
        [16, 17, 18]]])