In [6]:
"""Broadcasting means:

 NumPy automatically adjusts shapes
 So arrays of different sizes can work together

In simple words:
“NumPy stretches small arrays to match big ones"""

'Broadcasting means:\n\n NumPy automatically adjusts shapes\n So arrays of different sizes can work together\n\nIn simple words:\n“NumPy stretches small arrays to match big ones'

In [7]:
import numpy as np

In [8]:
arr=np.array([1,2,3,4,5])
res=arr**2  #vectorization-->Doing operations on many values at once
print(res)

[ 1  4  9 16 25]


In [9]:
res +10

array([11, 14, 19, 26, 35])

In [12]:
arr1=np.array([[1,2,3,],[4,5,6]])   #broadcating   2D
arr2=np.array([1,2,3])    #1D
print(arr1+arr2)

[[2 4 6]
 [5 7 9]]


In [13]:
data=np.array([[1,2,3],
               [4,5,6],
               [7,8,9],
               [10,11,12]
              ])

mean=data.mean(axis=0)   #1=row wise,,0=col wise  Col 0:(1+4+7+10)/4 = 5.5,Col 1: (2+5+8+11)/4 = 6.5,Col 2: (3+6+9+12)/4 = 7.5
std=data.std(axis=0)

#normalize=data-mean/std

normalized=(data-mean)/std
normalized

array([[-1.34164079, -1.34164079, -1.34164079],
       [-0.4472136 , -0.4472136 , -0.4472136 ],
       [ 0.4472136 ,  0.4472136 ,  0.4472136 ],
       [ 1.34164079,  1.34164079,  1.34164079]])