In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,4,6,4,3,7,5,3,6,6,6,6,6])

In [3]:
np.mean(arr)

np.float64(4.642857142857143)

In [4]:
np.std(arr)

np.float64(1.756910553749835)

In [6]:
np.var(arr)

np.float64(3.0867346938775517)

In [7]:
np.min(arr)

np.int64(1)

In [8]:
np.max(arr)

np.int64(7)

In [9]:
np.argmin(arr)   mini index

np.int64(0)

In [10]:
np.argmax(arr)

np.int64(6)

In [11]:
np.sum(arr)

np.int64(65)

In [12]:
np.prod(arr)

np.int64(470292480)

In [13]:
np.diff(arr)   #finds the difference between consecutive elements.

array([ 1,  2,  2, -2, -1,  4, -2, -2,  3,  0,  0,  0,  0])

In [14]:
np.percentile(arr, 50)  # For the 50th percentile (median)

np.float64(5.5)

In [16]:
# np.corrcoef(arr1, arr2)

In [17]:
np.unique(arr)  #removes dupli

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
np.cumsum(arr)

array([ 1,  3,  7, 13, 17, 20, 27, 32, 35, 41, 47, 53, 59, 65])

In [19]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.log(arr)

array([0.        , 0.69314718, 1.38629436, 1.79175947, 1.38629436,
       1.09861229, 1.94591015, 1.60943791, 1.09861229, 1.79175947,
       1.79175947, 1.79175947, 1.79175947, 1.79175947])

In [21]:
np.exp(arr)

array([   2.71828183,    7.3890561 ,   54.59815003,  403.42879349,
         54.59815003,   20.08553692, 1096.63315843,  148.4131591 ,
         20.08553692,  403.42879349,  403.42879349,  403.42879349,
        403.42879349,  403.42879349])